### PR TITLE
[AUTOMATIC] Release/4.8.0

### PR DESCRIPTION
**Pull request by RCGitBot**
**This is an automatic release.**

### New Features
* Change default usesStoreKit2IfAvailable to false (#587) via Cesar de la Vega (@vegaro)
* Adds StoreProduct.susbcriptionPeriod (#579) via Cesar de la Vega (@vegaro)
* Send customer info to first listener added (#576) via Toni Rico (@tonidero)
* Add beginRefundRequest APIs for iOS 15+ (#577) via Toni Rico (@tonidero)
### Bugfixes
* Fix integration tests (#584) via Cesar de la Vega (@vegaro)
* Fix macOS compilation (#582) via Cesar de la Vega (@vegaro)
### Dependency Updates
* [AUTOMATIC BUMP] Updates purchases-hybrid-common to 4.10.0 (#588) via RevenueCat Git Bot (@RCGitBot)
  * [Android 5.6.7](https://github.com/RevenueCat/purchases-android/releases/tag/5.6.7)
  * [iOS 4.17.2](https://github.com/RevenueCat/purchases-ios/releases/tag/4.17.2)
  * [iOS 4.17.1](https://github.com/RevenueCat/purchases-ios/releases/tag/4.17.1)
  * [iOS 4.17.0](https://github.com/RevenueCat/purchases-ios/releases/tag/4.17.0)

### CODE REVIEW

**Comment by NachoSoto** [comment]
Looks like the versions in the changelog got duplicated?

**Comment by vegaro** [comment]
Yeah, I haven't added that improvement yet. If there are two increases of phc in one release, it will add two entries

**Review by vegaro — APPROVED** [review]

**Comment by vegaro** [comment]
Looks like https://github.com/RevenueCat/purchases-flutter/pull/588/files broke the version number and some versions needed to be updated

**Comment by vegaro** [comment]
This looks the same issue https://github.com/flutter/flutter/issues/118469

**Comment by vegaro** [comment]
Looks like freezed also got updated and files are a bit different now, so updating those too

**Comment by vegaro** [comment]
Looks like freezed also got updated and files are a bit different now, so updating those too

**Pull request merged**
