### PR TITLE
Release/4.2.0

### PR DESCRIPTION
**Pull request by NachoSoto**
### Fixes
- Fixed crash when cancelling purchases (#403) via NachoSoto (@NachoSoto)

### Other Changes
* Updated `purchases-ios` to 4.10.2
* Re-enabled `SK2` as the default on iOS
* `PurchasesFlutterPlugin`: silenced unused warning (#444) via NachoSoto (@NachoSoto)
* `README`: removed `Amazon` note since it's now supported. (#442) via NachoSoto (@NachoSoto)
* Update fastlane plugin (#440) via Toni Rico (@tonidero)

### CODE REVIEW

**Review by taquitos — APPROVED** [review]
🚢 it

**Comment by aboedo** [comment]
I think it'd be safer to only make SK2 the default if we also introduce the option to roll back to sk1 in the configure method. 

That way, if anything goes wrong or unexpected (like yesterday's report of differences with intro eligibility), customers have an easy way to roll back. 

Could we add the option to `configure` first?

**Comment by NachoSoto** [comment]
That's a great point, I'll do that.

**Comment by NachoSoto** [comment]
Done: #450

**Comment by aboedo** [comment]
The added option will now make this a 4.2.0 release, right?

**Comment by NachoSoto** [comment]
Good point 👍🏻 not sure ill have time to do this today so if somebody wants to wake over feel free!

**Pull request merged**
