### PR TITLE
Release/3.4.2

### PR DESCRIPTION
**Pull request by aboedo**
## 3.4.2

- Fixed deprecation warnings for types used for compatibility with Flutter apps using Flutter < 1.12.
    https://github.com/RevenueCat/purchases-flutter/pull/232
- Bumped `purchases-hybrid-common` to 1.8.2. [Changelog here](https://github.com/RevenueCat/purchases-hybrid-common/releases/1.8.2)
    https://github.com/RevenueCat/purchases-flutter/pull/233

### CODE REVIEW

**Comment by aboedo** [comment]
tests are failing right now because of cached dependencies, it'll take a few mins before purchases-hybrid-common 1.8.2 propagates

**Comment by aboedo** [comment]
I'll re-run them manually in a bit

**Comment by aboedo** [comment]
all green now 🟢

**Review by beylmk — APPROVED** [review]
🐦

**Pull request merged**
