### PR TITLE
Release/5.8.1

### PR DESCRIPTION
**Pull request by tonidero**
### Dependency Updates
* Bump PHC 6.3.1 (#965) via Toni Rico (@tonidero)

### CODE REVIEW

**Comment by NachoSoto** [comment]
Hmm that's similar to what I fixed, but I guess coming from freezed?

**Comment by tonidero** [comment]
> Hmm that's similar to what I fixed, but I guess coming from freezed?

Yeah, the analyzer changes with each flutter version. Now we are running with the latest every time instead of being locked to a version, so that means these old branches are outdated and don't pass the analyzer anymore...

I could fix those, but I think it's better to minimize the changes

**Comment by tonidero** [comment]
Fixed freezed in `main` here: https://github.com/RevenueCat/purchases-flutter/pull/969

**Review by vegaro — APPROVED** [review]
:shipit:

**Comment by tonidero** [comment]
Release made. Closing PR.

**Pull request closed without merging**
